module.exports = [
  'is this a rug',
  'is this rug',
  'this project rug',
  'this team rug',
  'devs rug',
  'devs can rug',
  'team can rug',
  'team rug',
  'is drip rug',
  'is drip a rug',
  'is drip legit',
  'is this project legit',
  'when will titano rug',
  'how can I be sure drip is not a rug',
  'how can I be sure drip is not rug',
  "how can I be sure drip is not won't rug",
  'how can I be sure drip is not will not rug',
  'will drip rug',
  'when drip rug',
  'can drip rug',
  'can drip be a rug',
  'can this be rug',
  'is drip legit',
  'drip legit',
  'drip be legit',
];
